/*
 * Copyright 2007 Pieter De Rycke
 * 
 * This file is part of JMTP.
 * 
 * JTMP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as 
 * published by the Free Software Foundation, either version 3 of 
 * the License, or any later version.
 * 
 * JMTP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU LesserGeneral Public 
 * License along with JMTP. If not, see <http://www.gnu.org/licenses/>.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_derycke_pieter_com_COM */

#ifndef _Included_be_derycke_pieter_com_COM
#define _Included_be_derycke_pieter_com_COM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_derycke_pieter_com_COM
 * Method:    CoCreateInstance
 * Signature: (Lbe/derycke/pieter/com/CLSID;JJLbe/derycke/pieter/com/IID;)Lbe/derycke/pieter/com/COMReference;
 */
JNIEXPORT jobject JNICALL Java_be_derycke_pieter_com_COM_CoCreateInstance
  (JNIEnv *, jclass, jobject, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
