/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_derycke_pieter_com_OleDate */

#ifndef _Included_be_derycke_pieter_com_OleDate
#define _Included_be_derycke_pieter_com_OleDate
#ifdef __cplusplus
extern "C" {
#endif
#undef be_derycke_pieter_com_OleDate_serialVersionUID
#define be_derycke_pieter_com_OleDate_serialVersionUID 7523967970034938905i64
#undef be_derycke_pieter_com_OleDate_serialVersionUID
#define be_derycke_pieter_com_OleDate_serialVersionUID 6901412906760265708i64
/*
 * Class:     be_derycke_pieter_com_OleDate
 * Method:    setDate
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_be_derycke_pieter_com_OleDate_setDate
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     be_derycke_pieter_com_OleDate
 * Method:    toDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_be_derycke_pieter_com_OleDate_toDouble
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
