/*
 * Copyright 2007 Pieter De Rycke
 * 
 * This file is part of JMTP.
 * 
 * JTMP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as 
 * published by the Free Software Foundation, either version 3 of 
 * the License, or any later version.
 * 
 * JMTP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU LesserGeneral Public 
 * License along with JMTP. If not, see <http://www.gnu.org/licenses/>.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_PortableDeviceContentImplWin32 */

#ifndef _Included_jmtp_PortableDeviceContentImplWin32
#define _Included_jmtp_PortableDeviceContentImplWin32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_PortableDeviceContentImplWin32
 * Method:    createObjectWithPropertiesAndData
 * Signature: (Ljmtp/PortableDeviceValuesImplWin32;Ljava/io/File;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jmtp_PortableDeviceContentImplWin32_createObjectWithPropertiesAndData
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceContentImplWin32
 * Method:    createObjectWithPropertiesOnly
 * Signature: (Ljmtp/PortableDeviceValuesImplWin32;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jmtp_PortableDeviceContentImplWin32_createObjectWithPropertiesOnly
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceContentImplWin32
 * Method:    delete
 * Signature: (ILjmtp/PortableDevicePropVariantCollectionImplWin32;)V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceContentImplWin32_delete
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     jmtp_PortableDeviceContentImplWin32
 * Method:    listChildObjects
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jmtp_PortableDeviceContentImplWin32_listChildObjects
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jmtp_PortableDeviceContentImplWin32
 * Method:    getProperties
 * Signature: ()Ljmtp/PortableDevicePropertiesImplWin32;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDeviceContentImplWin32_getProperties
  (JNIEnv *, jobject);

/*
 * Class:     jmtp_PortableDeviceContentImplWin32
 * Method:    getObjectIDsFromPersistentUniqueIDs
 * Signature: (Ljmtp/PortableDevicePropVariantCollectionImplWin32;)Ljmtp/PortableDevicePropVariantCollectionImplWin32;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDeviceContentImplWin32_getObjectIDsFromPersistentUniqueIDs
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jmtp_PortableDeviceContentImplWin32
 * Method:    cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jmtp_PortableDeviceContentImplWin32_cancel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
