/*
 * Copyright 2007 Pieter De Rycke
 * 
 * This file is part of JMTP.
 * 
 * JTMP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as 
 * published by the Free Software Foundation, either version 3 of 
 * the License, or any later version.
 * 
 * JMTP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU LesserGeneral Public 
 * License along with JMTP. If not, see <http://www.gnu.org/licenses/>.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jmtp_PortableDevicePropertiesImplWin32 */

#ifndef _Included_jmtp_PortableDevicePropertiesImplWin32
#define _Included_jmtp_PortableDevicePropertiesImplWin32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jmtp_PortableDevicePropertiesImplWin32
 * Method:    getPropertyAttributes
 * Signature: (Ljava/lang/String;Ljmtp/PropertyKey;)Ljmtp/PortableDeviceValuesImplWin32;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDevicePropertiesImplWin32_getPropertyAttributes
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jmtp_PortableDevicePropertiesImplWin32
 * Method:    getValues
 * Signature: (Ljava/lang/String;Ljmtp/PortableDeviceKeyCollectionImplWin32;)Ljmtp/PortableDeviceValuesImplWin32;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDevicePropertiesImplWin32_getValues
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     jmtp_PortableDevicePropertiesImplWin32
 * Method:    setValues
 * Signature: (Ljava/lang/String;Ljmtp/PortableDeviceValuesImplWin32;)Ljmtp/PortableDeviceValuesImplWin32;
 */
JNIEXPORT jobject JNICALL Java_jmtp_PortableDevicePropertiesImplWin32_setValues
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
